### ISSUE TITLE
Useless #[link]

### ISSUE THREAD

**Issue by retep998** [lgvz/rust-opus#4]
https://github.com/lgvz/rust-opus/blob/master/opus-sys/src/lib.rs#L55
```Rust
#[link(name = "opus")]
```
This line is totally useless and makes build scripts override really difficult. Your build script should already tell Rust what library to link so there is no need for `#[link]` attributes. Build script overrides are pretty essential for people on Windows, especially those using the msvc version of Rust since your build script does not work in that environment.

**Comment by lgvz** [comment]
Thanks for reporting.
